title: SVUIT-MMTT
description: A study vault of UIT
theme: just-the-docs

url: https://svuit.github.io/mmtt

aux_links:
  Đóng góp cho website: https://svuit.github.io/mmtt/docs/contribute

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: pink
  new:
    title: New
    color: green
  note:
    title: Note
    color: darkblue
  warning:
    title: Warning
    color: red

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

favicon_ico: "/assets/images/favicon.ico"



gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SVUIT/mmtt" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html